# Generated by Django 3.2.10 on 2024-09-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('usuario', models.CharField(max_length=15)),
                ('temario', models.CharField(max_length=15)),
                ('titulo', models.CharField(max_length=15)),
                ('apunte', models.CharField(max_length=100)),
            ],
        ),
    ]
